# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongodb
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/data/db

  app:
    image: app
    command: jupyter notebook --ip 0.0.0.0 --port 80
    ports:
      - 80:80

volumes:
  mongo:
